name: Test-WorkFlow-RepoA-02

on:
  workflow_dispatch:
    inputs:
      custom_input:
        description: 'Triggered by Repo B'
        required: true
        default: 'No input provided'

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display Custom Input from Repo B
        run: |
            echo "Received input: ${{ github.event.inputs.custom_input }}"
